import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "../components/footer/footer";
import { Nav } from "../components/nav/nav";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.body}`}>
        <div style={{ paddingTop: 48 }}>
          <Nav />
        </div>
        <div>{children}</div>
        <div style={{ paddingBottom: 48 }}>
          <Footer />
        </div>
      </body>
    </html>
  );
}
